#
name: Automatic doc checks

on:
  workflow_call:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   paths:
  #     - "docs/**"
  #     - ".github/workflows/automatic-doc-checks.yml"
  # merge_group:
  #   types: [checks_requested]
  #   paths:
  #     - "docs/**"
  #     - ".github/workflows/automatic-doc-checks.yml"
  workflow_dispatch:
    # Manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
