name: Dynamic CI check

on:
  push:
    branches:
      - main
      - release/[0-9]+.[0-9]+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  file-changed:
    name: Filter Changed Files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      code_changes: ${{ steps.filter.outputs.code }}
      docs_changes: ${{ steps.filter.outputs.docs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect change type
        id: filter
        uses: dorny/paths-filter@v3
        with:
        #   base: ${{ github.event.merge_group.base_ref }}
        #   ref: ${{ github.event.merge_group.head_ref }}
          filters: |
            docs:
              - "docs/**"
              - ".github/workflows/automatic-doc-checks.yml"
            code:
              - "src/**"
              - "tests/**"
              - ".github/workflows/linux*"
              - ".github/workflows/windows-macos.yml"

  docs-lint:
    name: Doc checks
    needs: file-changed
    if: needs.file-changed.outputs.docs_changes == 'true'
    runs-on: ubuntu-latest
    steps:
    #   - uses: actions/checkout@v4
      - name: Build docs
        uses: ".github/workflows/automatic-doc-checks.yml"
    
#   build:
#     name: "Build & Test Sources"
#     needs: file-changed
#     if: needs.file-changed.outputs.code_changes == 'true'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: ".github/workflows/linux.yml"
