name: Linux

on:
  workflow_call:
  # push:
  #   branches:
  #     - main
  #     - release/[0-9]+.[0-9]+
  #   tags:
  #     - v[0-9]+.[0-9]+.[0-9]+
  # pull_request:
  #   types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  CheckLint:
    runs-on: ubuntu-latest

    outputs:
      conclusion: ${{ steps.check-lint.outputs.conclusion }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check Lint Status
        id: check-lint
        uses: ./.github/actions/check-lint
