name: WindowsMacOS

on:
  workflow_call:
  # push:
  #   branches:
  #     - main
  #     - release/[0-9]+.[0-9]+
  #   tags:
  #     - v[0-9]+.[0-9]+.[0-9]+
  # pull_request:
  #   types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.run_id }}
  cancel-in-progress: true

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: multipass-ci

jobs:
  CheckLint:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}

    outputs:
      conclusion: ${{ steps.check-lint.outputs.conclusion }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check Lint Status
        id: check-lint
        uses: ./.github/actions/check-lint
